title: Publish, by F.O
description: > # this means to ignore newlines until "baseurl:"
  For thoughts bigger than a Tweet.
  Minimalist, Explicit.
  I am a good person deep down inside.


baseurl: "/" # the subpath of your site, e.g. /blog
permalink: ':title/'
#url: "https://publish.felixogg.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: '@dromerdenker'

# Author Settings
author: F.O. # add your name
#author-img:  # add your photo
about-author: tbd # add description
social-twitter: dromerdenker # add your Twitter handle
#social-facebook: # add your Facebook handle
social-github: dromerdenker # add your Github handle
#social-linkedin: # add your Linkedin handle
#social-email: # add your Email address

# Disqus
#discus-identifier:  # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 1000
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
